[project]
name = "mygpt_ezhoureal"
version = "0.0.1"
authors = [
  { name="Tianer Zhou", email="ezhoureal@gmail.com" },
]
description = "An experimental GPT-2 implementation for learning purposes"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/ezhoureal/mygpt"
Documentation = "https://github.com/ezhoureal/mygpt#readme"