[project]
name = "mygpt_ezhoureal"
version = "0.0.1"
description = "An experimental GPT-2 implementation for learning purposes"
authors = [{ name = "Tianer Zhou", email = "ezhoureal@gmail.com" }]
requires-python = ">=3.9"
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
dependencies = [
    "maturin>=1.8.3",
    "pytest==8.3.5",
    "regex==2024.11.6",
    "tiktoken==0.9.0",
    "torch==2.6.0",
    "tqdm==4.67.1",
    "transformers==4.51.2",
]
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/ezhoureal/mygpt"
Documentation = "https://github.com/ezhoureal/mygpt#readme"

[tool.uv]
package = false

[tool.maturin]
bindings = "pyo3"
module-name = "tokenizer"
manifest-path = "tokenizer/Cargo.toml"

[build-system]
requires = ["maturin>=1.0"]
build-backend = "maturin"
